export const MERLOC_GATEKEEPER_ENABLE_ENV_VAR_NAME = 'MERLOC_GATEKEEPER_ENABLE';
export const MERLOC_GATEKEEPER_DEBUG_ENABLE_ENV_VAR_NAME =
    'MERLOC_GATEKEEPER_DEBUG_ENABLE';

export const MERLOC_GATEKEEPER_ENABLED =
    (process.env[MERLOC_GATEKEEPER_ENABLE_ENV_VAR_NAME] || 'true') === 'true';
export const MERLOC_GATEKEEPER_DEBUG_ENABLED =
    (process.env[MERLOC_GATEKEEPER_DEBUG_ENABLE_ENV_VAR_NAME] || 'false') ===
    'true';
