const MERLOC_GATEKEEPER_ENABLE_ENV_VAR_NAME = 'MERLOC_GATEKEEPER_ENABLE';
const MERLOC_GATEKEEPER_DEBUG_ENABLE_ENV_VAR_NAME =
    'MERLOC_GATEKEEPER_DEBUG_ENABLE';

const MERLOC_GATEKEEPER_ENABLED =
    (process.env[MERLOC_GATEKEEPER_ENABLE_ENV_VAR_NAME] || 'true') === 'true';
const MERLOC_GATEKEEPER_DEBUG_ENABLED =
    (process.env[MERLOC_GATEKEEPER_DEBUG_ENABLE_ENV_VAR_NAME] || 'false') ===
    'true';

module.exports = {
    MERLOC_GATEKEEPER_ENABLE_ENV_VAR_NAME,
    MERLOC_GATEKEEPER_DEBUG_ENABLE_ENV_VAR_NAME,

    MERLOC_GATEKEEPER_ENABLED,
    MERLOC_GATEKEEPER_DEBUG_ENABLED,
};
